version: "3"

services:
  app:
    build:
      context: ./
    container_name: ems-web
    restart: unless-stopped
    ports:
      - 4200:4200
    networks:
      - ems

networks:
  ems:
    name: ems
    external: true
